Добавляет наставника
htmlacademy-htmlcss/2037085-sedona-34 pull request #1
Opened 2022-05-18 21:52 UTC by Vishnevoenastroenie

2022-05-19 07:36 UTC, Dima-Dim requested changes

2022-05-19 07:36 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Привет! Отредактируй, пожалуйста, строку Наставник чтобы было по аналогии со строкой Студент. Для этого нужно добавить ссылку на мой профиль https://htmlacademy.ru/profile/dima

2022-05-22 21:09 UTC, Vishnevoenastroenie commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Доброго времени суток! Извините, что сразу не ответила. Ссылку добавила. А Ваши фамилию и имя нужно было тоже в квадратных скобочках писать? И ссылку в круглых скобочках, верно?   Это нормально, что я только коммит вижу, а новый пуллреквест не создался, хоть и нажимала ctrl+R?  В файле с изменениями я вижу исправленную строчку, но когда захожу со странички с заданием, нажимаю "Обновить пуллреквест", он ничего нового не находит (не появляется, как раньше, что Кексобот собрал пуллреквест). И Гитхаб пишет мне про какие-то две ветки. В этом диалоге ничего не появится, пока Вы не ответите на изменения предложенные? Извините, если это глупый вопрос, просто я не понимаю, увидите ли Вы эту исправленную строчку)))  Или это нормально, что всего лишь коммит новый появился? Он (коммит) в рамках этого пуллреквеста появился, и никакой новый пуллреквест и не должен был появиться (и Кексобот его не должен был собрать), и просто ещё раз на кнопочку  "Отправить на проверку" можно нажимать, и Вы увидите лишь этот коммит, да изменённую строчку?

2022-05-23 06:31 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
"А Ваши фамилию и имя нужно было тоже в квадратных скобочках писать? И ссылку в круглых скобочках, верно?" - если сомневаешься, то ты всё это можешь проверить и посмотреть что получится. Если получится то что нужно - верно, если нет, то нет :)

"Это нормально, что я только коммит вижу, а новый пуллреквест не создался" - верно. В разделе https://up.htmlacademy.ru/adaptive/25/help/5.1 должен быть описан алгоритм работы, что и когда создавать нужно, а когда не нужно.
Т.к. нового пуллриквеста нет, то и находить его не нужно. А нет его, потому что текущий ещё не принят и новый не был создан.

"увидите ли Вы эту исправленную строчку" - если ты зайдёшь в текущий пуллриквест и увидешь в нём присланные тобою изменения, то и я, если зайду в него тоже их увижу.

"Или это нормально, что всего лишь коммит новый появился?" - если ты был сделан один новый коммит, то кроме него ничего и не должно нового появиться.

2022-05-23 06:31 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
И да, сейчас всё сделано верно :)

2022-05-23 06:31 UTC, Dima-Dim approved these changes

2022-05-23 06:32 UTC, merged

2022-05-23 16:05 UTC, Vishnevoenastroenie commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Снова здравствуйте!

"Проверить, и посмотреть, что получится" - это сохранить написанный код в редакторе, и в браузере открыть эти сохранённые изменения, да? 

Поняла. Спасибо! К сожалению, по этой ссылке страница не находится.

Хорошо. Прояснилось в голове) Спасибо!

Можно ещё один вопрос (возможно странный? Если в процессе выполнения предстоящего домашнего задания у меня возникнут трудности/ уточнить что-то нужно будет (загуглю - не пойму, спрошу с дискорде - уже все спят) и время будет позднее - то есть в телеграмм уже нельзя будет писать после 20:00,    мне можно задавать Вам вопросы в этой (текущей) вкладке? Или тут только Ваши исправления? И Вам всё равно эти все уведомления на почту будут приходить, и мешать?

2022-05-23 17:48 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
> "Проверить, и посмотреть, что получится" - это сохранить написанный код в редакторе, и в браузере открыть эти сохранённые изменения, да?

В некоторых IDE есть режим просмотра md файлов и тогда сделать и посмотреть как оно выглядит. Если такого предвпросмотра в IDE нет, то сделать изменения, отправить коммит и посмотреть как отображается файл на GitHub. Т.е. не сам код, а орендеренная версия, в данном случае https://github.com/Vishnevoenastroenie/2037085-sedona-34/blob/e3320c62240b4be72c82de52f8e77c1c44e82b24/Readme.md

Здесь лучше писать вопросы в контексте конкретного задания. По новому заданию, для которого ещё нет пуллриквеста, лучше писать в телеграм.