index.html
htmlacademy-htmlcss/2037085-sedona-34 pull request #2
Opened 2022-05-26 11:20 UTC by Vishnevoenastroenie

2022-05-27 09:54 UTC, Dima-Dim requested changes

2022-05-27 09:54 UTC, Dima-Dim commented on index.html
> +            Поиск
Зачем тут скрытый текст если выше такой же не скрытый?

2022-05-27 09:54 UTC, Dima-Dim commented on index.html
> +      <section>
Как-то маловато там всего для section. Да и заголовок внутри можно использовать как h1, который сейчас скрытый.

2022-05-27 09:54 UTC, Dima-Dim commented on index.html
> +        <h3 class="advantages">СЕДОНА - НЕБОЛЬШОЙ ГОРОДОК В АРИЗОНЕ, ЗАСЛУЖИВАЮЩИЙ БОЛЬШЕГО!</h3>
Тексты нужно писать как мы обычно пишем, т.е. заглавные буквы в начале предложение, и если это какой либо бренд или абривиатура. Стализацию будем делать с помощью css.

2022-05-27 09:54 UTC, Dima-Dim commented on index.html
> +            <div class="advantage-image">
Для чего div? https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

2022-05-27 09:54 UTC, Dima-Dim commented on index.html
> +          <br>и мы покажем вам лучшие предложения гостиниц в Седоне
`<br>` тоже про стилизацию, не нужно их использовать сейчас.

2022-05-27 09:54 UTC, Dima-Dim commented on index.html
> +          <h3 class="form-header">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</h3>
Тут же нет какого-то развёрнутого текста, значит и озаглавливать нечего.

2022-05-27 09:54 UTC, Dima-Dim commented on index.html
> +                <span class="visually-hidden">ВКонтакте</span>
Вне ссылки, которую описывает этот текст, не особо имеет смысл.

2022-05-27 09:54 UTC, Dima-Dim commented on index.html
> +      <p class="about-text"><div class="html
`div` в `p`? https://validator.w3.org/nu/ Да и вообще зачем тут столько тегов?

2022-05-29 21:04 UTC, Vishnevoenastroenie commented on index.html
> +            Поиск
Доброго времени суток! 
Я хотела, для себя эту лупу "обозвать" поиском.
Получается, что в ссылке скринридер тоже прочитает "Поиск"?
То есть нужно скрывать и пункт списка, и ссылку? Оборачивать в  <span class="visually-hidden"> и ссылку и строчку с текстом? 

Или ничего и не скрывать, так как эту лупу только поиском и можно назвать?

2022-05-29 21:13 UTC, Vishnevoenastroenie commented on index.html
> +            Поиск
А скриридер "произносит" ссылки?

2022-05-29 21:32 UTC, Vishnevoenastroenie commented on index.html
> +      <section>
Хорошо. Удалила и переименовала заголовок.
Правильно я понимаю, что заголовки каждого порядка (с цифрой 1, к примеру) могут использоваться несколько раз? То есть это не порядковые номера заголовков, а категория? 
Как тогда понять, где ещё h2, к примеру, а где уже h3? Величина текста не всегда ведь показатель?

2022-05-29 21:46 UTC, Vishnevoenastroenie commented on index.html
> +        <h3 class="advantages">СЕДОНА - НЕБОЛЬШОЙ ГОРОДОК В АРИЗОНЕ, ЗАСЛУЖИВАЮЩИЙ БОЛЬШЕГО!</h3>
Понятно. Убрала.
В названиях же оставляем большие буквы тоже? 
- штат Аризона
- Мост Дьявола (тут тоже ведь с заглавной по идее (?)). Не дьявольский мост же, а Мост Дьявола. Туроператоры с заглавных букв оба слова в названии пишут

2022-05-29 22:00 UTC, Vishnevoenastroenie commented on index.html
> +            <div class="advantage-image">
Удалила. Заменила на span.
А span там нужен? "Пишут, что для группировки элементов в целях стилизации..."
 Что потом применять к картинке (?) 
Вообще удалить 58 строчку нужно?

2022-05-29 22:03 UTC, Vishnevoenastroenie commented on index.html
> +          <br>и мы покажем вам лучшие предложения гостиниц в Седоне
Понятно. Убрала

2022-05-29 22:46 UTC, Vishnevoenastroenie commented on index.html
> +          <h3 class="form-header">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</h3>
Хорошо. Удалила. Заменила на span. Подходит же он?

2022-05-29 22:50 UTC, Vishnevoenastroenie commented on index.html
> +                <span class="visually-hidden">ВКонтакте</span>
Извините. Не понимаю, что Вы хотите сказать...

136 и 137 строчку добавила, чтобы иконку VK скринридер прочитал как ВКонтакте.
Нужно убрать 137 строчку?

2022-05-29 23:17 UTC, Vishnevoenastroenie commented on index.html
> +      <p class="about-text"><div class="html
Не знаю, что и сказать...

<a class="button-link" href="https://htmlacademy.ru" aria-label="HTML Academy">Логотип HTML Academy</a>

Вот так можно переделать? Валидатор всё равно ругается, пишет, что неверный начальный тег.

2022-05-30 06:03 UTC, Dima-Dim commented on index.html
> +            Поиск
Какой смысл слова поиск самого по себе, без ссылки? Ну вот прочитает его скрин ридер и что? Что пользователь должен сделать с этой информацией?

2022-05-30 06:06 UTC, Dima-Dim commented on index.html
> +      <section>
Всё примерно так же как и с заголовками в книгах/рефератах. Может у книги/реферата быть два названия? Вот и у странице не нужно делать несколько h1.
https://developer.mozilla.org/ru/docs/Web/HTML/Element/Heading_Elements

2022-05-30 06:07 UTC, Dima-Dim commented on index.html
> +        <h3 class="advantages">СЕДОНА - НЕБОЛЬШОЙ ГОРОДОК В АРИЗОНЕ, ЗАСЛУЖИВАЮЩИЙ БОЛЬШЕГО!</h3>
Всё так же как и когда мы пишем обычный текст.

2022-05-30 06:09 UTC, Dima-Dim commented on index.html
> +            <div class="advantage-image">
> А span там нужен?

Нужен для чего? Если что тебе нужно, т.е. если тебе без чего-то совсем никак, ты это используешь. Не нужно что-то вставлять вразметку просто так или не зная зачем.

2022-05-30 06:10 UTC, Dima-Dim commented on index.html
> +          <h3 class="form-header">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</h3>
А почему не `p`?
https://up.htmlacademy.ru/htmlcss/34/book/1.6

2022-05-30 06:19 UTC, Dima-Dim commented on index.html
> +                <span class="visually-hidden">ВКонтакте</span>
Так же как и с поиском. К чему тут скрытый текст? Что пользователь должен с ним сделать?
Скрытые тексты не нужны просто так, более того, это тексты, которых вроде как по макету быть вовсе не должно, но мы их используем с какой-то очень важной целью. Во-первых для того, чтобы указать на названия блоков, там где это большие блоки и по названию можно было бы понять насколько он интересен и его нужно читать дальше. Во-вторых, чтобы рассказать что это за интерактивный элемент, с которым можно взаимодействовать. Возможно, ты видишь в этом ещё какой-то дополнительный смысл.
Повторюсь, не нужно вставлять в разметку что-то просто так, только, если в этом есть смысл и ты его точно понимаешь. Если не понимаешь, лучше вообще ничего не вставлять и дождаться темы, где об этом расскажут.

2022-05-30 06:19 UTC, Dima-Dim commented on index.html
> +      <p class="about-text"><div class="html
Не нужно у меня спрашивать разрешение :) У тебя есть валидатор и здравый смысл. Всё что под это подходит ты можешь использовать :)
Сотри этот участок кода и напиши его заново с учётом того, что я написал тебе ранее.

2022-05-31 17:51 UTC, Dima-Dim requested changes
1. В данном задании нет ничего про стили, в нём должна быть только разметка.
2. Перед отправко задания на проверку хорошо бы проверить html файлы валидатором https://validator.w3.org/nu/

2022-06-02 08:36 UTC, Dima-Dim requested changes
По мимо комментариев основные моменты, на которые нужно обратить внимание. Касаются всего кода.
1. Корректно расставить отступы для вложенных тегов. Если используешь VScode, то можно использовать плагин editorconfig
https://htmlacademy.ru/blog/articles/codeguide-why-what-and-how
https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-01

2. Не нужно использовать теги, в которых ничего нет, они засоряют разметку
https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

3. Не нужно делать лишних обёрток. Пока вы не приступили к стилизации, не ясно насколько они будут нужны.

4. Перечитать критерии.

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +        </a>
Нужно соблюдать отступы, иначе сходу сложно понять что во что вложено.

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +        <h3 class="advantages">Седона - небольшой городок Аризоне, заслуживающий большего!</h3>
Либо не нужно делать скрытый заголовок, либо следующий по вложенности заголовок будет уже h4.

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +            <span class="advantage-image"></span>
https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +            <div class="advantage-image">
Для чего тут div? Это тоже нарушает критерий https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +      <header class="search-header">
Нет тут особого смысла и в header, и вообще в лишнем контейнере.

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +      <div class="form-title">
Тоже лишний контейнера в виде div-а.

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +            <span class="visually-hidden">ВКонтакте</span>
Не верное использование скрытого текста, мы это обсуждали голосом.

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +        <h2 class="visually-hidden">Контактный телефон</h2>
Не нужно добавлять скрытые заголовки ко всему.

2022-06-02 08:36 UTC, Dima-Dim commented on index.html
> +          <p class="about-text">+7(812)812-12-12</p>
О том как правильно добавить телефон по критериям https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-05

2022-06-02 08:36 UTC, Dima-Dim commented on catalog.html
> +            <input type="submit" name="apply-filter" value="Применить">
Для чего инпут? Что в него нужно ввести?

2022-06-02 08:36 UTC, Dima-Dim commented on catalog.html
> +            <button type="reset" name="clean-filter" value="Сбросить"></button>
https://up.htmlacademy.ru/htmlcss/34/criteries#ALLY-02

2022-06-02 08:36 UTC, Dima-Dim commented on catalog.html
> +              <section class="hotel-description">
Нету здесь секций, это довольно маленькая карточка.

2022-06-02 08:36 UTC, Dima-Dim commented on catalog.html
> +            <h3 class="visually-hidden">Гостиница Amara Resort & Spa</h3>
Зачем скрытый заголовок если чуть ниже такой же но видимый?

2022-06-02 08:36 UTC, Dima-Dim commented on catalog.html
> +                <p class="hotel-type-price">
Где закрывается этот p? Пожалуйста, внимательнее с тегами. Нормальные отступы при их вложенности помогают следить за этим.

2022-06-02 08:36 UTC, Dima-Dim commented on catalog.html
> +              <div class="hotel-stars stars-4">
Почему div, а не p?

2022-06-02 08:36 UTC, Dima-Dim commented on catalog.html
> +                            <p class="your-e-mail"></p>
Что за пустой тег?

2022-06-03 06:41 UTC, Dima-Dim commented on catalog.html
> +            <p class="about-text">+7(812)812-12-12</p>
Как нужно оформлять номер телефону указано в критерии https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-03
Правки можешь вносить уже в следующем задании.

2022-06-03 06:41 UTC, Dima-Dim commented on index.html
> +              <input type="text" name="+7(812)812-12-12">
Это не input, сюда пользователь никакие данные не вводит.

2022-06-03 06:43 UTC, merged

2022-06-03 18:14 UTC, Vishnevoenastroenie commented on catalog.html
> +            <p class="about-text">+7(812)812-12-12</p>
Здравствуйте! Спасибо! То есть,  телефон, как ссылку вставляем? <a href="tel:+78128121212">+7 812 812-12-12</a>