Добавляет стилизацию пока только главной страницы
htmlacademy-htmlcss/2037085-sedona-34 pull request #4
Opened 2022-06-07 01:43 UTC by Vishnevoenastroenie

2022-06-08 15:03 UTC, Dima-Dim commented on styles/styles.css
> +  background-image: url("images/decorative-elements/index-background.jpg");
Не верный url для изображения. Увидеть проблему можно посмотрев опубликованную версию, запустив девтулзы.

2022-06-08 15:04 UTC, Dima-Dim commented on styles/styles.css
> +  font-style: Regular;
Нет такого значения у свойства `font-style`.

2022-06-08 15:05 UTC, Dima-Dim commented on styles/styles.css
> +/* А вот эти фоновые картинки, которые должны быть растянуты, как-то можно объединить, чтобы только одну запись с одинакомыми параметрами для них создать? */
Да, это должно быть одним файлом.

2022-06-08 15:06 UTC, Dima-Dim commented on styles/styles.css
> +.hotel-title {hotel-title
Здесь явно опечатка.

2022-06-08 16:14 UTC, Vishnevoenastroenie commented on index.html
> +      <img class="index-background" src="images/decorative-elements/index-background.jpg" width="1200" height="485" alt="Фоновое изображение гор.">
Доброго вечера! Просто в задании было сказано: "достаточно подключить несколько крупных фоновых изображений или текстур".   Значит можно     оставить одно изображение в разметке, добавить ему класс "фоновое изображение" и всё? Остальные фоновые иным образом подключаются в следующих заданиях? И из папки тоже лишние удалить, чтобы они не попали под статью "неиспользуемые изображения"?

2022-06-08 16:15 UTC, Vishnevoenastroenie commented on index.html
> +    <img class="blurred-mountains" src="images/decorative-elements/blurred-mountains.jpg" width="1200" height="411" alt="Размытые горы.">
Удаляю с остальными фоновыми, кроме одной, верно?

2022-06-08 16:15 UTC, Vishnevoenastroenie commented on styles/styles.css
> +/* Если в макете не было наклонного шрифта, его сюда нужно подключать было "на потом"? */
Понятно. Удаляю.

2022-06-08 16:16 UTC, Vishnevoenastroenie commented on styles/styles.css
> +/* Если в макете не было полужирного наклонного шрифта, его сюда нужно подключать было "на потом"? */
Хорошо. Удаляю

2022-06-08 16:33 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.hotel-title {hotel-title
Нужно писать names of hotels?

2022-06-08 19:22 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  background-image: url("images/decorative-elements/index-background.jpg");
Получается, мне нужно было удалить эту картинку. Только одну сказали оставить. Нет картинки- нет неправильного местонахождения ? Или вся эта уйма ошибок в консоли была по одинаковой причине, которую ещё нужно как-то исправлять?

2022-06-09 04:16 UTC, Dima-Dim requested changes
Я вижу что ты вносила правки, но не вижу что проверяла как они отобразились в опубликованной версии.
На странице https://htmlacademy-htmlcss.github.io/2037085-sedona-34/4/catalog.html есть не загружающееся изображенияни и в целом на сайте не загружаются шрифты, это тоже видно в девтулзах.

2022-06-09 04:27 UTC, Vishnevoenastroenie commented
Доброго утра! Да. Остались только три ошибки вот эти. Я открывала в браузере. Смотрела эти вкладки. А почему они не загружаются?  Как-то неправильно их подключила? 
![В Дискорд вопрос](https://user-images.githubusercontent.com/105811068/172764129-7c4781db-07a7-4902-a174-40e8fc04b66e.jpg)

2022-06-09 04:32 UTC, Vishnevoenastroenie commented
Убрала одну точку в пути. Всё равно ошибки не уходят

2022-06-09 04:43 UTC, Vishnevoenastroenie commented
![image](https://user-images.githubusercontent.com/105811068/172765645-36d484b3-9956-4810-bf03-d7e65ab0eeea.png)
                                                                                                                                                                                            Пробовала 3 варианта пути. Никак не уходят. Вот два последних варианта. 1.И папку гитхаб указала. 2. С фонтс начала.     Ещё до этого с двумя точками были пути. Тоже не подходило

2022-06-09 05:02 UTC, Vishnevoenastroenie commented
![image](https://user-images.githubusercontent.com/105811068/172768126-8a89c90b-4468-4a82-a4ce-30696425982c.png)

 До меня дошло) Одна ошибка только осталась в консоли

2022-06-09 05:04 UTC, Vishnevoenastroenie commented
![Правильные пути к шрифрам](https://user-images.githubusercontent.com/105811068/172768345-da3add81-34c0-4cb8-b204-ab09bbf8a76b.jpg)

2022-06-09 05:10 UTC, Dima-Dim commented on index.html
> +      <img class="index-background" src="images/decorative-elements/index-background.jpg" width="1200" height="485" alt="Фоновое изображение гор.">
Во-первых, ты здесь подключила явно не фоновые изображения, а контентные.
Можно оставить контентное изображение. Если ему добавить `класс "фоновое изображение"`, что бы это не значило, но фоновым от этого оно не станет. У Вас в материалах была целая статья про изображения и то, какими они бывают.
Всё это можно сделать одним изображением.
Всё что не используется в проекте не должно быть в репозитории.

2022-06-09 05:13 UTC, Dima-Dim commented on index.html
> +    <img class="blurred-mountains" src="images/decorative-elements/blurred-mountains.jpg" width="1200" height="411" alt="Размытые горы.">
Это само по себе замечание, никак не относящееся ко всем остальному. Данное изображение не является контентным и его не должно быть в разметке. Как и что с этим сделать ты должна знать из материалов курса.

2022-06-09 05:16 UTC, Dima-Dim commented on styles/styles.css
> +  background-image: url("images/decorative-elements/index-background.jpg");
> Нет картинки- нет неправильного местонахождения ?

Да, нет кода, нет ошибок.

> Или вся эта уйма ошибок в консоли была по одинаковой причине, которую ещё нужно как-то исправлять?

Я указал тебе на наличие проблемы и даже указал на то, почему она происходит. Хорошо бы далее самостоятельно проанализировать ситуацию и прийти к каким-то выводам.

2022-06-10 04:48 UTC, Dima-Dim commented
Всё ещё не вижу что ты проверяешь как выглядит опубликованная версия.
И в ней всё ещё есть ошибки в консоли https://htmlacademy-htmlcss.github.io/2037085-sedona-34/4/

2022-06-10 05:07 UTC, Vishnevoenastroenie commented
Доброго утра! Почему так может быть? В лайф-сервере нет ошибок, кроме той с плагином. В версии, которая по ссылке открывается, все старые ошибки, будто я ничего не делала... Проверяю. Еще вчера присылала скрин с одной ошибкой. Вроде каждую строчку уже коммичу и запушиваю

![Screenshot_1](https://user-images.githubusercontent.com/105811068/172994278-0c902ce4-d457-495e-b511-398181b6685d.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/105811068/172994285-1e429dce-a6d4-4ae3-951c-70d81210f44e.jpg)

2022-06-10 23:50 UTC, Vishnevoenastroenie commented
Доброго времени суток! По Вашей рекомендации нажала кнопку "Опубликовать". Потом нужно было подождать от 15 минут. Подождала. Перешла по ссылке "Опубликованная версия", а ошибок уже и нет)))  Значит, когда я вечером сразу переходила, показывались ещё неисправленные ошибки получается, верно? Днём я значит правильно откорректировала. Попробовала зайти и из интерфейса академии, и из письма, которое Вы мне присылали после предыдущей проверки. Только та ошибка плагина висит. 

https://user-images.githubusercontent.com/10581

https://user-images.githubusercontent.com/105811068/173163557-4a96336d-f5b0-491f-a277-0546d0a6911e.mp4

1068/173163543-eacf20e5-f44c-4623-b33f-443ea6806454.mp4

2022-06-11 04:55 UTC, Dima-Dim commented
> Доброго утра! Почему так может быть? В лайф-сервере нет ошибок, кроме той с плагином. В версии, которая по ссылке открывается, все старые ошибки, будто я ничего не делала... Проверяю. Еще вчера присылала скрин с одной ошибкой. Вроде каждую строчку уже коммичу и запушиваю
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/105811068/172994278-0c902ce4-d457-495e-b511-398181b6685d.jpg) ![Screenshot_2](https://user-images.githubusercontent.com/105811068/172994285-1e429dce-a6d4-4ae3-951c-70d81210f44e.jpg)

Потому что разные сервера работают по разному и ресурсы сайтов размещают по разному. Локальный сервер максимально не привередлив, можно так сказать. У него всё рядом и как захочешь, а вот на стороннем сервисе могут быть ограничения и условия более привередливые.

2022-06-11 04:56 UTC, Dima-Dim commented
> Доброго времени суток! По Вашей рекомендации нажала кнопку "Опубликовать". Потом нужно было подождать от 15 минут. Подождала. Перешла по ссылке "Опубликованная версия", а ошибок уже и нет))) Значит, когда я вечером сразу переходила, показывались ещё неисправленные ошибки получается, верно? Днём я значит правильно откорректировала. Попробовала зайти и из интерфейса академии, и из письма, которое Вы мне присылали после предыдущей проверки. Только та ошибка плагина висит.
> 
> https://user-images.githubusercontent.com/10581
> Video.2022-06-11.02-47-45-961.mp4
> 
> 1068/173163543-eacf20e5-f44c-4623-b33f-443ea6806454.mp4

Да, судя по видео, ошибки исправлены.

2022-06-11 05:01 UTC, merged