5.22. Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2037085-sedona-34 pull request #5
Opened 2022-06-16 08:29 UTC by Vishnevoenastroenie

2022-06-17 12:12 UTC, Dima-Dim requested changes
Крупные сеточные блоки должны быть расположены по макет. Например, преимущества по макету не все в один ряд. Тоже самое карточки на странице catalog.html
За одно поменяй ссылку на страницу каталога в верхнем меню.

2022-06-17 12:12 UTC, Dima-Dim commented on index.html
> +      <h1 class="visually-hidden" hidden>Welkome to the gorgeous</h1>
Не нужно делать на странице больше 1-го h1, иначе его смысл теряется.

2022-06-17 12:12 UTC, Dima-Dim commented on index.html
> +      <img class="white-carved-element" src="images/decorative-elements/white-carved-element.svg" width="1200" height="57" alt="Белый резной элемент.">
Название просто кричит это декоративный элемент, которого не должно быть в разметке.

2022-06-17 12:12 UTC, Dima-Dim commented on catalog.html
> +              <a class="button" href="https://vk.com/htmlacademy"></a>
https://up.htmlacademy.ru/htmlcss/34/criteries#ALLY-02

2022-06-21 03:59 UTC, Vishnevoenastroenie commented
Доброго утра! Прикрепляю скрины с финальных стадий в демках 5 раздела (верх) и в своём проекте (нижняя часть фото). Основное меню сверху обвела салатовым, карточки на странице  каталога цвета фуксии обводка. Карточки нам рекомендовали сделать на гридах, а пока оставить в таком состоянии.  Вроде также у меня всё. Или я не вижу какие-то различия? В чём тогда они  (различия)  по сравнению с финальным состоянием этих объектов в 5 разделе?  Уже в 6 в строчку меню ведь будут делать? И в 8 разделе с помощью гридов карточки
![Screenshot_1](https://user-images.githubusercontent.com/105811068/174713422-d904190f-26d1-4f80-ae93-78a2a8795e37.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/105811068/174713436-83568cde-cc8f-4b1c-95b7-92c879f0eb69.jpg)


?

2022-06-21 13:38 UTC, merged