6.18. Микросетки на флексах для всех страниц
htmlacademy-htmlcss/2037085-sedona-34 pull request #6
Opened 2022-06-22 01:20 UTC by Vishnevoenastroenie

2022-06-22 03:21 UTC, Dima-Dim requested changes

2022-06-22 03:21 UTC, Dima-Dim commented on index.html
> +                <img class="advantages-images" src="images/content-images/a-real-town.jpg" width="800" height="384" alt="Седона-настоящий городок.">
Мы вроде говорил о том, что это изображение не сам по себе отдельный пункт списка?

2022-06-22 03:21 UTC, Dima-Dim commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Размещать тут 3 изображения можно но не оптимально с точки зрения оптимизации по загрузке ресурсов.

2022-06-22 03:21 UTC, Dima-Dim commented on index.html
> +            <h2 class="visually-hidden">Welkome to the gorgeous</h2>
Нет смысла в таком количестве скрытых заголовков. Достаточно одного.

2022-06-22 03:21 UTC, Dima-Dim commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
Думаю понятно что это тоже не отдельный пункт списка.

2022-06-22 03:21 UTC, Dima-Dim commented on styles/styles.css
> +.sedona-white{
Смотря на такое название класса можно понять для чего он может быть использован? Я то могу догадаться, потому что знаю проект, а если человек не настолько хорошо в него погружен?

2022-06-22 03:21 UTC, Dima-Dim commented on styles/styles.css
> +  margin-top: 0;
На что влияет это свойство? Для чего оно нам? Если его не было бы что-то сломалось бы? Далее так же есть такие же свойства с непонятным назначением.

2022-06-22 03:21 UTC, Dima-Dim commented on styles/styles.css
>    display: flex;
Для чего тут display: flex;? Какую задачу он решает?

2022-06-22 03:21 UTC, Dima-Dim commented on styles/styles.css
> +  margin-left: 30px;   /*Так как     padding-inline-start: 40px;*/
"padding-inline-start: 40px;" но компенсируем мы это с помощью margin? Почему не переопределяем с помощью padding?

2022-06-22 03:21 UTC, Dima-Dim commented on styles/styles.css
> +.logo-html-academy .button-link-html{
Для чего тут вложенность селекторов? .button-link-html используется где-то ещё?

2022-06-22 05:55 UTC, Vishnevoenastroenie commented on index.html
> +                <img class="advantages-images" src="images/content-images/a-real-town.jpg" width="800" height="384" alt="Седона-настоящий городок.">
Да. Написала уточняющее сообщение в ТГ

2022-06-22 05:55 UTC, Vishnevoenastroenie commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Написала уточняющее сообщение в ТГ

2022-06-22 05:59 UTC, Vishnevoenastroenie commented on index.html
> +            <h2 class="visually-hidden">Welkome to the gorgeous</h2>
Хорошо. Удалила второй

2022-06-22 06:01 UTC, Vishnevoenastroenie commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
Да. Я по этой ситуации задала вопрос в ТГ. Можно ли тогда картинку в <div> обернуть, чтобы и местоположение не потерять, и валидатор чтобы не ругался на валяющиеся картинки между пунктами списка

2022-06-22 06:15 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  margin-top: 0;
Ни на что. Написала более понятное "sedona-slogan".  И одноимённый класс соответственно. Объединила свойства из двух прошлых классов в этот один. Ничего не случилось)

2022-06-22 06:21 UTC, Vishnevoenastroenie commented on styles/styles.css
>    display: flex;
![image](https://user-images.githubusercontent.com/105811068/174957102-a4c2352f-59c0-4f10-b84d-0c107dbf1e37.png)
 Это я в материалах прочитала 6.6. Вложенные флексы. Чтобы содержимое растянулось. Текст элайн центер делал совсем не похоже на макет.      Продублировала ответ в ТГ, чтобы легче было обсудить

2022-06-22 06:36 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  margin-left: 30px;   /*Так как     padding-inline-start: 40px;*/
Переопределила. Просто это выглядело как внешний отступ слева от квардратиков.  Внешне ничего не должно было измениться?  Продублировала это обсуждение в ТГ, так как здесь неудобно диалог вести. Всё приходит не знамо когда
![image](https://user-images.githubusercontent.com/105811068/174959872-ad4cc6ec-e80e-44ce-afd5-6b7b63952c6b.png)

2022-06-22 06:48 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.logo-html-academy .button-link-html{
Да. Это я их разъединяла. Сама картинка логотипа без отступа для клика. У неё паддинга 38 нет (пространство для расширения клика кнопки),  и кнопка с этим паддингом 38 (расстояние до края страницы - больше область клика нельзя было сделать, так как это самое близкое расстояние до края страницы).    Обсуждение продублировала в ТГ
![image](https://user-images.githubusercontent.com/105811068/174962289-a58b20c2-315c-42dd-a83c-b2c462895e73.png)

2022-06-22 08:31 UTC, Dima-Dim commented on styles/styles.css
> +.logo-html-academy .button-link-html{
Я имел ввиду для чего используется вложенность селекторов при стилизации? Почему не просто `.button-link-html`, а именно `.logo-html-academy .button-link-html`?

2022-06-22 08:34 UTC, Dima-Dim commented on styles/styles.css
>    display: flex;
Растянулось по высоте или ширине? Чуть точнее, какую именно задачу ты пыталась решить?

2022-06-22 08:35 UTC, Dima-Dim commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
Давай поставлю вопрос по другому? Что является 1-ым элементом списка? Что в него входит?

2022-06-22 08:36 UTC, Dima-Dim commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Здесь понятно относительно чего происходит диалог, в тегеграм нет, там одна общая лента и нет когда, который обсуждается.

2022-06-22 08:49 UTC, Vishnevoenastroenie commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Нам просто говорили, что они контентные (это я относительно того, что в разметку их поместила) и что их нужно делать именно тремя изображениями, и потом позиционировать. Объясняли, что "к великолепному to-the-gorgeous" потом может захотеться заказчику поменять на "к горам", например.   Все изображения оптимизированы в SVGOMG.   Нельзя оставить? Нужно объединить "Добро пожаловать в великолепие" в одну картинку?

2022-06-22 08:50 UTC, Vishnevoenastroenie commented on index.html
> +                <img class="advantages-images" src="images/content-images/a-real-town.jpg" width="800" height="384" alt="Седона-настоящий городок.">
Да. Мы разговаривали, что изображение не может быть дочерним элементом списка неупорядоченного <u>l. Я их обернула внутрь <li>, чтобы и валидатор не ругался, и очерёдность не нарушилась. Так нельзя было?  Они и внутри  <li> не могут быть?  Почему тогда валидатор не отмечал это ошибками? Сейчас сняла обёртки. Валидатор, конечно же не пропускает. Вынесу за список <ul>   - они сместятся. Можно их в <div> обернуть?

2022-06-22 08:51 UTC, Vishnevoenastroenie commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
Да. Мы разговаривали, что изображение не может быть дочерним элементом списка неупорядоченного <u>l. Я их обернула внутрь <li>, чтобы и валидатор не ругался, и очерёдность не нарушилась. Так нельзя было?  Они и внутри  <li> не могут быть?  Почему тогда валидатор не отмечал это ошибками? Сейчас сняла обёртки. Валидатор, конечно же не пропускает. Вынесу за список <ul>   - они сместятся. Можно их в <div> обернуть?

2022-06-22 08:53 UTC, Vishnevoenastroenie commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
В первый пункт списка я обернула картинку, чтобы валидатор не ругался. Её нужно было обернуть в див? Просто, если вынести её за список, то она отображается совсем в другом месте

2022-06-22 08:55 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.sedona-white{
Исправила на понятное название. Объединила в один селектор свойства. Ничего не сломалось

2022-06-22 08:56 UTC, Vishnevoenastroenie commented on styles/styles.css
>    display: flex;
По высоте. Правда не помогло, и я выставила минимальную высоту. Но текст расположился более похоже на макет

2022-06-22 10:38 UTC, Dima-Dim commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
Вопрос был следующим: Что является 1-ым элементом списка? Что в него входит?

2022-06-22 10:41 UTC, Dima-Dim commented on styles/styles.css
>    display: flex;
Значит нужно было разобраться почему не помогло.

2022-06-22 13:57 UTC, Vishnevoenastroenie commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Да я бы рада всё поудалять. Просто при проверке другим наставником перед защитой не возникнет проблем? Несколько раз нам подчёркивали, что нужно их разделять...

2022-06-22 14:04 UTC, Vishnevoenastroenie commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
Если Вы имеете ввиду 1 пунтк неупорядоченного списка <ul>, то в него входит дочерний флекс "Настоящий городок" - блок с текстом на тёмно-голубом фоне    
![image](https://user-images.githubusercontent.com/105811068/175048250-6594fe14-c686-4a13-8e81-e99b244e9d66.png)
  Просто выше скрин 88, 89,94,95 строчек. И там внутри пункта списка <li> находится картинка. Текстовые блоки и картинки - неравнозначные пункты неупорядоченного списка? Нельзя так оборачивать? Но как "вывести из игры" картинки, чтобы они не потеряли свое местоположение (позицию) на сайте?

2022-06-22 14:24 UTC, Vishnevoenastroenie commented on styles/styles.css
>    display: flex;
![image](https://user-images.githubusercontent.com/105811068/175053530-dcc90f3d-cec4-49c3-8002-7bf6f3c7b144.png)

2022-06-22 14:31 UTC, Vishnevoenastroenie commented on styles/styles.css
>    display: flex;
А flex-direction: column. самому тексту можно было задать? Он выстроился бы в колоночку?

2022-06-22 17:20 UTC, Dima-Dim commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Я не могу тебе давать гарантий о случайных наставниках.

2022-06-22 17:21 UTC, Dima-Dim commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
"в него входит дочерний флекс "Настоящий городок" - блок с текстом на тёмно-голубом фоне" - а чем является тогда изображение?

2022-06-22 17:24 UTC, Dima-Dim commented on styles/styles.css
>    display: flex;
Слишком много схем ради обычного элемента с display: block; который задан по умолчанию. Не нужно пытаться использовать магию flex, там где нужно просто корректно задать размеры элементов в потоке.

2022-06-22 17:30 UTC, Vishnevoenastroenie commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Я понимаю) Но Вы разрешаете так оставить? Вдруг, кто-то из них посчитает ошибкой это, так как нас несколько раз предупреждали

2022-06-22 17:39 UTC, Vishnevoenastroenie commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
Изображение само по себе. Ему никогда в жизни не нужно задавать дисплей-флекс))) Просто как бы изображения вызволить из этого списка (пункты которого все флексы, но с другим классом, нежели у изображений (чтобы эта вся "магия флекса" не воздействовала на изображения)),        чтобы они (изображения находились потом в нужном месте?    В этом тренажёре, вот, изображение помещено в пункт списка... Неверно, или их можно помещать так? 
![image](https://user-images.githubusercontent.com/105811068/175101854-1a034f5a-d15c-4504-ad96-1f2e91b360c7.png)

2022-06-22 17:43 UTC, Vishnevoenastroenie commented on styles/styles.css
>    display: flex;
Так значит всех этих элементов нужно убрать дисплей флекс, и ничего не сломается? А потом просто текст элайн сентер применить, и всё будет похоже на макет?

2022-06-22 17:46 UTC, Vishnevoenastroenie commented on styles/styles.css
>    display: flex;
А там, где домик, бургер и подарок? Как потом на нужно место установить эти изображения? Это никак не повлияет? Просто с помощью отступов?

2022-06-22 18:59 UTC, Vishnevoenastroenie commented on styles/styles.css
>    display: flex;
Указание именно минимальной высоты допустимо в данной случае?

2022-06-22 20:26 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.logo-html-academy .button-link-html{
![image](https://user-images.githubusercontent.com/105811068/175129636-41189946-5a48-4b6b-abe2-c298c9aa884c.png)
 Вот так теперь. Верно всё?

2022-06-22 23:19 UTC, Vishnevoenastroenie commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
А можно вынести изображение за пределы списка, и "order" ему задать порядок, чтобы на нужное место установилось?

2022-06-23 04:39 UTC, Dima-Dim commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Моё дело рассказать как оно есть, а ты можешь это исправлять или нет. Я могу принять задание и в таком виде.

2022-06-23 04:43 UTC, Dima-Dim commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
"Изображение само по себе. Ему никогда в жизни не нужно задавать дисплей-флекс" - причём тут флекс? Вопрос про логику. Т.е. это изображение само по себе оно ни к чему не относится и оказалось там просто для стилистике. На нём не изображён Настоящий городок и оно не иллюстрируют первый элемент списка. Так же как и в твоём примере изображение мандарина само по себе и не имеет никакого отношения к первой карточке где речь о мандарине?

2022-06-23 04:46 UTC, Dima-Dim commented on styles/styles.css
>    display: flex;
"Так значит всех этих элементов нужно убрать дисплей флекс" на самом деле его не нужно изначально указывать, чтобы не убирать, это код написанный ради кода, а любой код нужно писать только если без него совсем никак не обойтись.

"А там, где домик, бургер и подарок? Как потом на нужно место установить эти изображения? Это никак не повлияет? Просто с помощью отступов?" - это вам расскажут в разделе про декоративные элементы.

"А может можно обойтись только отступами?" если это решит задачу, то почему нет?

2022-06-23 04:48 UTC, Dima-Dim commented on styles/styles.css
>    display: flex;
"С боков выставить мерджин ноль авто, а сверху и снизу измерить и добавить?" - ещё раз. Твоя задача написать только тот код, без которого не получается добиться соответствия макета. Минимальное количество кода. Если нужны маржины и без них никак, добавляй. Если нужны паддинги и без них никак, добавляй. И так далее.

2022-06-23 04:50 UTC, Dima-Dim commented on styles/styles.css
> +.logo-html-academy .button-link-html{
Ты можешь проверить в браузере какие у кого теперь свойства, откуда и как они получаются и понять изменилось ли там что-то.

2022-06-23 04:53 UTC, Dima-Dim commented on index.html
> +                <img class="advantages-images" src="images/content-images/devil's-bridge.jpg" width="800" height="384" alt="Мост Дьявола.">
"А можно вынести изображение за пределы списка, и "order" ему задать порядок, чтобы на нужное место установилось?" - можно вместо вёрстки вставить просто изображение всей страницы, но мы учимся делать семантичную и доступную вёрстку. Оторвать изображение от пункта списка, который оно иллюстрируется это не доступно. По этому вы с начала делаете разметку. Логичную, семантичную, доступную и понятную. А потом её стилизуете, а не ломаете всё это потому что не получается всё это стилизовать.

2022-06-23 12:14 UTC, Vishnevoenastroenie commented on index.html
> +            <img class="slogan sedona-white" src="images/content-images/sedona-because-the-grand-canyon-sucks.svg" width="457" height="213" alt="Sedona. Because the Grand Canyon sucks!">
Извините. Это я неправильно лекторов поняла. Говорили, что  могут захотеть изменить фоновую на главной. И чтобы её не объединяли с белым резным элементом. Всё переделала.

2022-06-23 13:16 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.logo-html-academy .button-link-html{
Проверила. Там марджин относился именно к кнопке, а не к ссылке. Исправила

2022-06-25 10:11 UTC, Dima-Dim commented on catalog.html
> +            <p class="hotel-found"><b>Найдено гостиниц: 38</b></p>
b - здесь лишний тег.

2022-06-25 10:11 UTC, Dima-Dim commented on styles/styles.css
> +figure{
https://up.htmlacademy.ru/htmlcss/34/criteries#CSS-02

2022-06-25 10:12 UTC, merged

2022-06-25 10:16 UTC, Vishnevoenastroenie commented on styles/styles.css
> +figure{
Да. Помню, что нельзя так делать. Но по-другому. Просто margin: 0; у класса, относящегося к тегу figure не действовало. Как правильно нужно было поступить?

2022-06-25 10:23 UTC, Vishnevoenastroenie commented on catalog.html
> +            <p class="hotel-found"><b>Найдено гостиниц: 38</b></p>
Убрала. Запушу при выполнении следующего ДЗ, верно? Получается, тексту нужно добавить класс, и описать потом стили в ЦСС?        Ещё вопрос. Не в данном случае, а в целом. Есть много заголовков с одинаковыми параметрами текста. Можно, когда новые заголовки будут встречаться с такими же параметрами, прибавлять к ним через пробел класс, в котором уже прописаны эти одинаковые параметры текста? Чтобы меньше стилей было

2022-06-25 10:36 UTC, Dima-Dim commented on styles/styles.css
> +figure{
Так же как и со всеми остальными тегами, задать класс и стилизовать по нему.

2022-06-25 10:37 UTC, Dima-Dim commented on catalog.html
> +            <p class="hotel-found"><b>Найдено гостиниц: 38</b></p>
Да. Вам должны были показывать это. В этом и смысл CSS.

2022-06-25 10:48 UTC, Vishnevoenastroenie commented on styles/styles.css
> +figure{
Я поняла. У меня ничего не обнулилось, так как апостроф в названии класса в ЦСС стоял на тот момент. А в разметке не было апострофа в названии класса devils-bridge.    У меня и дисплей-флекс по этой же причине не применялся, и ничего не выстраивалось сначала

2022-06-25 10:48 UTC, Vishnevoenastroenie commented on styles/styles.css
> +figure{
Сейчас убрала этот селектор по тегу, и ничего не изменилось, так как названия классов уже совпадают, и всё действует