Выстраивает карточки отелей с помощью гридов
htmlacademy-htmlcss/2037085-sedona-34 pull request #7
Opened 2022-06-26 02:16 UTC by Vishnevoenastroenie

2022-06-26 03:05 UTC, Dima-Dim requested changes
Катало с карточками всё ещё далёк от крупной сетки макета.

2022-06-26 03:05 UTC, Dima-Dim commented on styles/styles.css
> + display: grid;
Для чего здесь грид? Обычный поток сверху вниз. Не нужно усложнять то, что усложнять не нужно.

2022-06-26 03:05 UTC, Dima-Dim commented on styles/styles.css
> +  display: block;
А без этого свойства разве его значения какое-то другое?

2022-06-26 03:05 UTC, Dima-Dim commented on styles/styles.css
> +.button-search-hotel{   /*Белый текст на белом фоне пока не видно*/
Что тебе мешает решить эту проблему? Это должно было быть сделано ещё на уровне базовой стилизации.

2022-06-26 03:05 UTC, Dima-Dim commented on styles/styles.css
> +  grid-column: 2/3;
А вот это для чего?

2022-06-26 03:05 UTC, Dima-Dim commented on styles/styles.css
> +.hotel{   /*Изображения отелей*/
Нет, не изображения отелей, судя по названию класса просто отель :)

2022-06-26 03:05 UTC, Dima-Dim commented on styles/styles.css
> +.hotel-type-price{    /*2 строчки друг напротив друга - гостиница и цена*/
Для 2х строчек друг на против друга у нас есть кое-что по проще.

2022-06-26 03:05 UTC, Dima-Dim commented on styles/styles.css
> +.pagination-item:not(:first-child){                        /*  not(:first-child)  А как светлой кнопку первую сделать? Отдельный класс для неё?*/
А если потом эти кнопки местами поменяют? Нужно будет идти в css искать почему у их цвета поменялись?

2022-06-26 14:11 UTC, Vishnevoenastroenie commented on catalog.html
> +              <article class="Desert-Quail-Inn hotel-card">
Здравствуйте! Убрала

2022-06-26 14:13 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.content-centering{    /*Как установить отступы по 40 пикселей слева и справа у всего сайта?*/
Вот эти две серые полосы по бокам сайта 
![image](https://user-images.githubusercontent.com/105811068/175818337-14a3a217-708f-4377-9a3e-2ae23530ad47.png)
По 40 пикселей они

2022-06-26 14:15 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  width: 1200px;       /*padding-left:40px;      padding-right:40px; у этого контейнера? В материалах так написано, но почему паддинг-то, если это внешние поля?*/
7.8. Методика построения сеток на гридах 
![image](https://user-images.githubusercontent.com/105811068/175818466-2ae2d981-d0c6-47fc-970f-ddfe608df1ce.png)

2022-06-26 14:16 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  width: 1200px;       /*padding-left:40px;      padding-right:40px; у этого контейнера? В материалах так написано, но почему паддинг-то, если это внешние поля?*/
Или это вообще не применительно к этим серым полосам по краям сайта Седоны?

2022-06-26 14:23 UTC, Vishnevoenastroenie commented on styles/styles.css
> + display: grid;
Нам, просто Андрей Середкин сказал, что можно сделать флексом/гридом. У внутреннего блока задать ширину, и поставить его "тупо по центру". И не нужны будут не марджины не паддинги.  Просто мне не понятно было, чью ширину там задавать, и я строчек наделала

Или у внешнего белого блока поставить падинги, а у блока внутреннего (с текстом) ничего тогда уже не задавать

2022-06-26 14:29 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  grid-column: 2/3;
Про то, чтобы вся карточка с 2 по третью колонку выстроилась, я сама не знаю, как поставила. Конечно, они по три не становились.  А эти размеры полос я написала по аналогии с тем, как нам Николай Шабалин показывал оформление самой карточки 
![image](https://user-images.githubusercontent.com/105811068/175819169-4912539d-53e5-4806-940d-f57c0cc017bf.png)

2022-06-26 14:30 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  grid-column: 2/3;
Сейчас убрала всю эту строчку. Ничего не сломалось

2022-06-26 14:35 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.hotel{   /*Изображения отелей*/
Исправила

2022-06-26 14:38 UTC, Vishnevoenastroenie commented on styles/styles.css
> + display: grid;
Но, честно говоря, я не очень понимаю про блоки. А это не просто текст, кроме кнопки?

2022-06-26 14:40 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  display: block;
Нет). Убрала

2022-06-26 14:50 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.button-search-hotel{   /*Белый текст на белом фоне пока не видно*/
Сделала

2022-06-26 14:55 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.pagination-item:not(:first-child){                        /*  not(:first-child)  А как светлой кнопку первую сделать? Отдельный класс для неё?*/
А зачем первую кнопку с какой-то поменяют?

2022-06-26 15:17 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.hotel-type-price{    /*2 строчки друг напротив друга - гостиница и цена*/
align-content: space-between;  ?   
Классам  "hotel-type-price, hotel-links, hotel-rating"

2022-06-26 16:53 UTC, Vishnevoenastroenie commented on styles/styles.css
> + display: grid;
Переделала без него

2022-06-26 16:56 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.hotel-type-price{    /*2 строчки друг напротив друга - гостиница и цена*/
Нет. Вот так 
![image](https://user-images.githubusercontent.com/105811068/175825291-6f509f29-e880-4568-a742-5e4600b656ae.png)

2022-06-26 17:15 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.pagination-item:not(:first-child){                        /*  not(:first-child)  А как светлой кнопку первую сделать? Отдельный класс для неё?*/
Или это она светлая, потому что в макете состояние, когда на первой странице находишься? То есть нужно было убрать это ограничение (кроме первого дочернего) из ЦСС?

2022-06-26 17:45 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.pagination-item:not(:first-child){                        /*  not(:first-child)  А как светлой кнопку первую сделать? Отдельный класс для неё?*/
Сделала я эту кнопку. Только у всех кнопок цифры не по центру. Это паддингами делается? Или есть что-то проще?

2022-06-27 01:33 UTC, Dima-Dim commented on styles/styles.css
> +  width: 1200px;       /*padding-left:40px;      padding-right:40px; у этого контейнера? В материалах так написано, но почему паддинг-то, если это внешние поля?*/
То, что на скрине зелёным это же ты сама написала? :) Нет там ничего такого. Раньше было явно определено что то, что упирается в края макета, тянется на всё ширину вьюпорта. Где это сейчас указано не знаю, но это вполне логично. У пользователя может быть широкий монитор. И что у него должно быть по краям в этом случае? В случае с Седоной вот этот серый фон, а не полоски в 40 px.

2022-06-27 01:35 UTC, Dima-Dim commented on styles/styles.css
> + display: grid;
Сделать можно очень по разному, но нужно же постараться выбрать какой-то оптимальный вариант.

2022-06-27 01:39 UTC, Dima-Dim commented on styles/styles.css
> +.pagination-item:not(:first-child){                        /*  not(:first-child)  А как светлой кнопку первую сделать? Отдельный класс для неё?*/
> А зачем первую кнопку с какой-то поменяют?

Затем что придёт, например, маркетолог и скажет что так кликать на них будут лучше. Вообще мы с тобой вроде говорил о том, что сайт это не монолит, который один раз сделали и забыли. Им пользуются люди, от них остаётся какая-то обратная связь и по ней, и не только, вносятся изменения. И задача в том числе в том, чтобы иметь возможность быстро и без проблем эти изменения иметь возможность вносить. Об этом вам тоже должны были рассказывать.

2022-06-27 01:40 UTC, Dima-Dim commented on styles/styles.css
> +.pagination-item:not(:first-child){                        /*  not(:first-child)  А как светлой кнопку первую сделать? Отдельный класс для неё?*/
> Только у всех кнопок цифры не по центру. Это паддингами делается? Или есть что-то проще?

Делается это выравниванием контента по центру :) У вас к этому моменту уже явно не один вариант для этого должен быть.

2022-06-27 01:41 UTC, Dima-Dim commented on styles/styles.css
> +.hotel-type-price{    /*2 строчки друг напротив друга - гостиница и цена*/
Как вариант. Это же проще чем грид городить?

2022-06-27 01:44 UTC, Dima-Dim commented on styles/styles.css
> +.pagination-item:not(:first-child){                        /*  not(:first-child)  А как светлой кнопку первую сделать? Отдельный класс для неё?*/
Ну и да, поведение отображения этих кнопок может быть разным. В одном случае первой всегда будет текущая страница, а в другом первой может всегда оставаться первая страница, которая уже не активна и тогда работать это будет не корректно. Думаю это более реалистичный сценарий с демонстрацией проблемы.

2022-06-27 02:02 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  width: 1200px;       /*padding-left:40px;      padding-right:40px; у этого контейнера? В материалах так написано, но почему паддинг-то, если это внешние поля?*/
Зелёным - да - это я поверх скрина написала.
То есть не смущаться этими 40 пикселями по краям в макете? И ничего не делать?

2022-06-27 02:03 UTC, Vishnevoenastroenie commented on styles/styles.css
> + display: grid;
Да. Я просто переделала, как Вы сказали

2022-06-27 02:09 UTC, Dima-Dim requested changes

2022-06-27 02:09 UTC, Dima-Dim commented on styles/styles.css
> +  width: 1200px;       /*padding-left:40px;      padding-right:40px; у этого контейнера? В материалах так написано, но почему паддинг-то, если это внешние поля?*/
Ну сделать нужно как в макете, но 40px это частный случай. В релаьности серый фон должен упираться в край вьюпорта, т.е. тянутся на всё ширину экрана.

2022-06-27 02:09 UTC, Dima-Dim commented on styles/styles.css
> +.hotel-type-price, hotel-links, hotel-rating{
Каждый новый селектор лучше переносить на новую строку, так они легче читаются. А ещё, если это селектор класса, а не тега, то перед ним ставиться точка.

2022-06-27 02:14 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.pagination-item:not(:first-child){                        /*  not(:first-child)  А как светлой кнопку первую сделать? Отдельный класс для неё?*/
Понятно. Сделала по центру

2022-06-27 02:24 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.hotel-type-price{    /*2 строчки друг напротив друга - гостиница и цена*/
Да. Сделала. Но всё ровненько по краям только при комбинации со свойством дисплей-грид у этих же элементов 
![Без грида](https://user-images.githubusercontent.com/105811068/175848357-910e7509-975b-403f-85c0-2321faeef092.jpg)
![С гридом](https://user-images.githubusercontent.com/105811068/175848363-2ef51205-74ac-4e82-b1b1-3787a237d0bd.jpg)

2022-06-27 02:26 UTC, Vishnevoenastroenie commented on styles/styles.css
> +.hotel-type-price, hotel-links, hotel-rating{
Сделала 
![image](https://user-images.githubusercontent.com/105811068/175848554-dbd3f14f-9edd-425b-9a6c-e053730b3a40.png)

2022-06-27 02:31 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  width: 1200px;       /*padding-left:40px;      padding-right:40px; у этого контейнера? В материалах так написано, но почему паддинг-то, если это внешние поля?*/
То есть нужно поместить в котейнер всё-всё-всё (боди) и добавить паддинг-лефт 40 и паддинг райт 40? У меня уже есть такой контейнер - сюда дописать, верно?
![image](https://user-images.githubusercontent.com/105811068/175849025-cb979299-0d05-4a91-8de1-8a650c69f160.png)

2022-06-27 07:53 UTC, Vishnevoenastroenie commented on styles/styles.css
> +  width: 1200px;       /*padding-left:40px;      padding-right:40px; у этого контейнера? В материалах так написано, но почему паддинг-то, если это внешние поля?*/
Всё хорошо. Мне ответили, что не нужно ничего добавлять)))
![image](https://user-images.githubusercontent.com/105811068/175888631-5108eee9-335d-4d0d-acd9-904e5f18b915.png)

2022-06-28 02:28 UTC, merged